name: Develop CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.DEADV_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          GIT_CONFIG_NAME: Aaron52077
          GIT_CONFIG_EMAIL: chao_code520@163.com
          COMMIT_MESSAGE: gh-pages deploy
  sync:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:Aaron52077/react-visual-data.git'
          destination-repo: 'git@gitee.com:wuli-admin/react-wuli-admin.git'

  reload-pages:
    needs: sync
    runs-on: ubuntu-latest

    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: Aaron52077
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: wuli-admin/react-wuli-admin
          branch: gh-pages,
          https: true
