name: Develop CI

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - ".github/workflows/*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install and Build
        run: yarn && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.DEADV_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          GIT_CONFIG_NAME: Aaron52077
          GIT_CONFIG_EMAIL: chao_code520@163.com
          COMMIT_MESSAGE: gh-pages deploy
