name: Develop CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Step Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          GITHUB_TOKEN: ${{ secrets.DEADV_DEPLOY_PRIVATE_KEY }}
          BRANCH: gh-pages
          FOLDER: gh-pages
          GIT_CONFIG_NAME: Aaron52077
          GIT_CONFIG_EMAIL: chao_code520@163.com
          COMMIT_MESSAGE: gh-pages deploy
  
   sync:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_TOKEN }}
        with:
          source-repo: 'git@github.com:Aaron52077/react-visual-data.git'
          destination-repo: 'git@gitee.com:wuli-admin/react-wuli-admin.git'

    reload-pages:
      needs: sync
      runs-on: ubuntu-latest

      steps:
        - name: Build Gitee Pages
          uses: yanglbme/gitee-pages-action@main
          with:
            gitee-username: Aaron52077
            gitee-password: ${{ secrets.GITEE_PASSWORD }}
            # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
            gitee-repo: "git@gitee.com:wuli-admin/react-wuli-admin.git"
            # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
            branch: gh-pages
